"""
Django settings for Review_site project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# Django 프로젝트의 전역 설정을 담당하는 파일
## Django 어플리케이션의 동작을 제어하는 설정과 구성을 정의

### DEBUG : 디버그 모드 여부 설정 (디버그 모드에서는 오류 메시지 표기, 개발 중인 코드 변경 사항이 자동으로 반영)
### DATABASES : 데이터베이스 연결 설정을 정의하는 변수 (데이터 베이스 종류, 호스트, 포트, 사용자 이름, 비밀 번호 설정 가능)
### INSTALLED_APPS : Django 어플리케이션의 설치된 앱 목록을 정의하는 변수 (새로운 앱을 추가하거나 기존 앱을 제거할 때 이 변수를 수정)
### STATIC_URL : 정적 파일의 URL과 실제 파일이 위치할 디렉토리를 설정하는 변수
### MEDIA_URL : : 미디어 파일(사용자가 업로드한 파일)의 URL과 실제 파일이 저장될 디렉토리를 설정하는 변수
### TEMPLATES : 템플릿 엔진 설정을 정의하는 변수
### LANGUAGE_CODE : 언어 코드와 시간대를 설정하는 변수

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wn8n-hgr^)@%3mv$2jk42_kia$towuxp*-yb6!jdjd^l2xp)if'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
   "fd75-125-243-178-81.ngrok-free.app"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap4',
    'widget_tweaks',
    'Reviews',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Review_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Review_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# 미디어 파일 경로 설정(1)
MEDIA_URL = '/media/' # 미디어 파일을 접근할 때 사용하는 url -> /MEDIA_URL/review_images/image_name
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # 미디어 파일이 존재하는 경로를 언급

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
